version: "3.9"

services:
  app:
    container_name: nextjs
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../app:/workspaces/container/app
    ports:
      - "3000:3000"
    user: node
    stdin_open: true
    tty: true
