name: ci

on:
  push:
  workflow_dispatch:

env:
  API_KEY: ${{secrets.API_KEY}}
  API_ENDPOINT: ${{secrets.API_ENDPOINT}}
  DRAFT_TOKEN: ${{secrets.DRAFT_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test
