name: ci

on:
  push:
  workflow_dispatch:

env:
  API_KEY: ${{secrets.API_KEY}}
  API_ENDPOINT: ${{secrets.API_ENDPOINT}}
  DRAFT_TOKEN: ${{secrets.DRAFT_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install
        run: cd app
        run: yarn install

      - name: Linting
        run: cd app
        run: yarn lint

      - name: Testing
        run: cd app
        run: yarn test
