name: develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  API_KEY: ${{secrets.API_KEY}}
  API_ENDPOINT: ${{secrets.API_ENDPOINT}}
  DRAFT_TOKEN: ${{secrets.DRAFT_TOKEN}}
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: yarn install
        run: yarn install

      - name: Run jest
        run: yarn test
